baseURL = 'https://lysng.github.io/themiette/'
title = 'The Miette'
theme = "minimo"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = ""
startYear = "2020"
suffix = " · made with ❤️ with the Minimo theme for Hugo"

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search", "taxonomy_cloud"]
footer = ["social_menu"]

[params.social]
email = ""
instagram = "heyelysee"

[params.search]
client = "fuse" # algolia / fuse / lunr

[outputs]
  home = ["HTML", "JSON", "RSS"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[params.comments]
enable = true

[params.comments.utterances]
enable = true
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"
crossorigin="anonymous"


[params.comments.utterances.github]
username = "lysng"
repository = "themiette"

disqusShortname = ""

[[menu.main]]
name = "About"
weight = -10
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Posts"
weight = -10
identifier = "Posts"
url = "/posts/"

[[menu.main]]
name = "Resources"
weight = -10
identifier = "Resources"
url = "/resources/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[[params.customCSS]]
href = "pathToFileUnderStatic"

[markup]
  [markup.tableOfContents]
    startLevel = 4
    endLevel = 6
    ordered = false